# agent.py

from langchain_nvidia_ai_endpoints import ChatNVIDIA

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.tools import tool

from config import LLM_MODEL


# --------------------------------------------------
# Create BNS agent and rewrite chain
# --------------------------------------------------

def create_bns_agent(retriever, format_docs):

    # --------------------------------------------------
    # Main LLM
    # --------------------------------------------------

    llm = ChatNVIDIA(
        model=LLM_MODEL
    )


    # --------------------------------------------------
    # BNS RAG TOOL
    # --------------------------------------------------

    @tool
    def bns_rag(query: str) -> str:
        """
        Retrieve relevant sections and text from
        the Bharatiya Nyaya Sanhita, 2023.
        """

        results = retriever.invoke(query)

        print(
            f"Retrieved {len(results)} documents"
        )

        return format_docs(results)


    # --------------------------------------------------
    # LLM TOOL CALLING
    # --------------------------------------------------

    retrieval_llm = llm.bind_tools(
        [bns_rag],
        tool_choice="required"
    )


    # --------------------------------------------------
    # FINAL ANSWER PROMPT
    # --------------------------------------------------

    answer_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """
You are a legal assistant specializing in the
Bharatiya Nyaya Sanhita, 2023.

Answer the user's question ONLY using the
retrieved BNS context.

Rules:

- Do not use IPC.
- Do not use outside legal sources.
- Do not invent sections, punishments,
  offences, or interpretations.
- Mention the relevant BNS section when available.
- If the retrieved context is insufficient,
  clearly say so.
- Answer directly and concisely.
- Do not mention tools, retrieval,
  prompts, or internal reasoning.
"""
        ),
        (
            "human",
            """
User question:

{question}

Retrieved BNS context:

{context}
"""
        )
    ])


    answer_chain = (
        answer_prompt
        | llm
        | StrOutputParser()
    )


    # --------------------------------------------------
    # CONTROLLED AGENT
    # --------------------------------------------------

    def run_agent(question):

        # --------------------------------------------------
        # Ask LLM to make ONE tool call
        # --------------------------------------------------

        tool_request = retrieval_llm.invoke(
            question
        )


        # Get tool calls generated by the LLM
        tool_calls = tool_request.tool_calls


        # Safety check
        if not tool_calls:

            return (
                "I could not retrieve the relevant "
                "BNS provision."
            )


        # --------------------------------------------------
        # Execute ONLY THE FIRST tool call
        # --------------------------------------------------

        tool_call = tool_calls[0]

        retrieval_query = tool_call["args"]["query"]


        print(
            "\nRetrieval query:",
            retrieval_query
        )


        # Actual BNS tool execution
        context = bns_rag.invoke(
            retrieval_query
        )


        # --------------------------------------------------
        # Generate final answer
        # --------------------------------------------------

        answer = answer_chain.invoke({
            "question": question,
            "context": context
        })


        return answer


    # --------------------------------------------------
    # QUESTION REWRITING
    # --------------------------------------------------

    rewrite_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """
Convert the latest user question into ONE standalone
question for retrieving information from the
Bharatiya Nyaya Sanhita, 2023.

Use conversation history only to resolve references
such as:

- it
- this
- that offence
- the accused
- its punishment
- he
- she
- minor

Output ONLY the rewritten question.

Do not explain anything.
Do not provide reasoning.
Do not provide multiple questions.
"""
        ),
        (
            "human",
            """
Conversation history:

{history}

Latest question:

{question}
"""
        )
    ])


    # --------------------------------------------------
    # Separate LLM for rewriting
    # --------------------------------------------------

    rewrite_llm = ChatNVIDIA(
        model=LLM_MODEL
    )


    rewrite_chain = (
        rewrite_prompt
        | rewrite_llm
        | StrOutputParser()
    )


    # --------------------------------------------------
    # Return controlled agent + rewrite chain
    # --------------------------------------------------

    return run_agent, rewrite_chain